project:
  type: website
  output-dir: docs
  
website:
  title: "Measurement error"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Special topics"
        contents:
          - exercise-1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

