---
title: "Measurement error"
---

This is the landing page for practical exercises related to the topic **survey measurement error**, from the Utrecht University summer course *S16: survey research*.

The slides can be found here: <https://daob.nl/files/S16-measurement-error-slides.pdf>

The exercises themselves can be found in the navigation bar to the left. At the moment, the only available exercises are those regarding *estimation* of measurement error: <https://daob.github.io/measurement-error/exercise-1.html> **\<\-- CLICK HERE TO START DOING THE EXERCISES**

Many people have the inituition that purely random measurement error can only *attenuate* regression coefficients (i.e. bias them towards zero). If this were so, then ignoring measurement error would be a "conservative" thing to do, in the sense that any strong relationships found in a linear regression could not be explained away by measurement error.

Unfortunately, **this intuition is false**. It is, in fact, perfectly possible for regression coefficients to become *inflated* due to completely random measurement error.

This point is illustrated in the Shiny app under this link: <https://daob.shinyapps.io/measurement-error/>, which you may be interested to take a look at. Note there are four separate slides (pages) in this app. On slide 4, you can observe the regression coefficient of the categorical independent variable (the gap between the lines) becoming inflated as you increase the amount of random measurement error variance.

The slides, current page, and the exercises were created by [me](https://daob.nl/about-me "A little more information about me (Daniel Oberski)").
